variable "tenancy_ocid" {}
variable "compartment_ocid" {}
variable "ssh_public_key" {}
variable "instance_shape" {}
variable "image_ocid" {}
variable "master_label" {}
variable "agent_label" {}
variable "instance_count" {}
variable "subnet" {}
variable "db_size" {}
variable "nfs_volume" {}
variable "ssh_private_key" {}
