variable tenancy_ocid {}
variable bucket {}
variable ssh_public_key_path {}
variable swift_password {}
variable region {}
variable subnet {}
variable PaaSJCSName {}
variable user {}
variable password {}
variable domain {}
variable tenancy {}
variable object_storage_user {}
variable PaaSDBName {}
variable DBShape {}
variable JCSShape {}
variable sid {}
variable DBPassword {}
variable weblogic_pwd {}
variable availability_domain {}
